#!/bin/sh
set -ex
SCRIPT_DIR=$(dirname "$(realpath "$0")")
LINUX_DIR=${1:-$SCRIP_DIR}
cd ${LINUX_DIR}

ARCH=x86
if [ ! -d arch/${ARCH} ] ; then
    ARCH=i386
fi

TARGET=oldnoconfig
if make -q ARCH=${ARCH} ${TARGET} ; then
    make ARCH=${ARCH} ${TARGET}
fi
make ARCH=${ARCH} bzImage
